#!/usr/bin/expect -f

#exp_internal 1

# Set the timeout for the expect command
set timeout 30

# Run the shell script and expect the password prompt
spawn ./inner_build_and_upload.sh
expect "Enter your API token:*"
# Send the password
send "pypi-AgEIcHlwaS5vcmcCJGNkZTRhODViLWUyZWQtNDA4Zi1iMjM3LTI1YWI5MGE4Yzk0MQACKlszLCI5ZWY4MmRmMS1hZmExLTRhZDMtOTI1MC1lNWI0Njc4ZjVmMWYiXQAABiDz-RCuTEvl6cSMieFHA6gSgZvu4m7sIx987Gn_BjgOSw"
send "\r"
# Wait for the script to complete
expect eof